### ISSUE TITLE
[Bug] [DataStudio] After defining variables in the registration center -> global variables and enabling global variables in data development, an error is reported in Yarn Application and the variables cannot be parsed correctly.

### ISSUE THREAD

**Issue by xjiahai** [DataLinkDC/dinky#2973] opened 2024-01-10 05:52 UTC
### Search before asking

- [X] I had searched in the [issues](https://github.com/DataLinkDC/dinky/issues?q=is%3Aissue) and found no similar issues.

### What happened

在注册中心->全局变量定义变量后在数据开发中启用全局变量后在Yarn Application中报错，不能正确解析变量，而在Yarn Per-Job中执行正常，以下是Yarn Application Flink报错截图
![image](https://github.com/DataLinkDC/dinky/assets/21072848/35594052-0c06-4801-9180-ca5728e82c45)

在注册中心->数据源定义Flink 连接配置后在数据开发中启用全局变量后在Yarn Application中报错Non-query expression encountered in illegal context，而在Yarn Per-Job是没问题的，从代码上分析是因为这个原因导致了Non-query expression encountered in illegal context，可以以下Flink执行日志截图
![image](https://github.com/DataLinkDC/dinky/assets/21072848/842d5474-d2a3-497b-98fd-08773d9e3af1)

上述在Yarn Per-Job执行没有问题是在1.0.0-rc3版本上，在之前版本均有问题，请知晓

### What you expected to happen

应该是yarn Application 执行时dinky-app这个有问题，变量处理方法与客户端提交有区别，这个我在看0.7.5代码时就发现了，估计是一样的问题

### How to reproduce

在注册中心->全局变量定义变量后在数据开发中启用全局变量后在Yarn Application中报错，不能正确解析变量，而在Yarn Per-Job中执行正常，以下是Yarn Application Flink报错截图
![image](https://github.com/DataLinkDC/dinky/assets/21072848/35594052-0c06-4801-9180-ca5728e82c45)

在注册中心->数据源定义Flink 连接配置后在数据开发中启用全局变量后在Yarn Application中报错Non-query expression encountered in illegal context，而在Yarn Per-Job是没问题的，从代码上分析是因为这个原因导致了Non-query expression encountered in illegal context，可以以下Flink执行日志截图
![image](https://github.com/DataLinkDC/dinky/assets/21072848/842d5474-d2a3-497b-98fd-08773d9e3af1)

上述在Yarn Per-Job执行没有问题是在1.0.0-rc3版本上，在之前版本均有问题，请知晓

### Version

1.0.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by gaoyan1998** [comment] 2024-01-10 12:31
Duplicate of #2970

**Comment by aiwenmo** [comment] 2024-01-12 14:35
Thanks for your feedback. We will fix it.

**Closed as completed** 2024-03-09 15:50 UTC
Labels: Bug, Invalid, P1
